module.exports = {
  8: "KEEP ON MOVIN\'",
  20: "La Se\ñorita",
  21: "La Se\ñorita Virtual",
  52: "CAN\'T STOP FALLIN IN LOVE(SPEED MIX)",
  60: "SANA MOLLETE NE ENTE",
  61: "CANDY *",
  63: "Healing Vision - Angelic Mix -",
  66: "Orion.78\~civilization mix\~",
  74: "CANDY <3",
  96: "Kakumei",
  98: "LOVE LOVE SUGAR",
  106: "Colors - for EXTREME -",
  117: "I\'m gonna get you!",
  138: "V \~for EXTREME \~",
  141: "Sakura",
  144: "Daikenkai",
  153: "CAN\'T STOP FALLIN IN LOVE - super euro version -",
  174: "Jam \& Marmalade",
  175: "KEEP ON MOVIN\' \~DMX MIX\~",
  217: "Konoko no nanatsu no oiwaini",
  221: "Gekkou chou",
  222: "DAN-DAN-DO",
  224: "Nijiiro",
  227: "AM-3P (CHAOS Special)",
  229: "B4U (VOLTAGE Special)",
  233: "CaptivAte - Chikai",
  234: "D2R (FREEZE Special)",
  235: "DEAD END (GROOVE RADAR Special)",
  246: "L\'amour et la liberte(DDR Ver.)",
  332: "Polyrhythm",
  333: "Kakumei (X-Special)",
  359: "I\'m So Happy",
  361: "KIMONO PRINCESS",
  402: "Delta MAX",
  403: "Fuchinkan CANDY",
  404: "Mei",
  405: "Beautiful Receipt",
  427: "CRAZY LOVE",
  428: "Sumidagawa karenka",
  452: "Tenjoy no hoshi \~reimeiki\~",
  453: "Terrible Hit Chart",
  456: "Alstroemeria (walk with you remix)",
  459: "osaka EVOLVED - maido, ohkini! - (TYPE 1)",
  460: "osaka EVOLVED - maido, ohkini! - (TYPE 2)",
  461: "osaka EVOLVED - maido, ohkini! - (TYPE 3)",
  482: "KEEP ON MOVIN (Y Co. DJ BOSS remix)",
  489: "Kouen",
  492: "Qipchaq",
  495: "Meumeupettantan",
  505: "Orenai heart",
  527: "Rakiraki",
  528: "Seiten Bon Voyage",
  530: "Nijiiro no hana",
  531: "Okome no oishii takikata, soshite okome wo taberu koto ni yoru sono kouka.",
  532: "Genesis Notes",
  541: "JoJo ~sono chi no sadame~",
  542: "Furisodation",
  549: "Kiken na kajitsu",
  550: "Who floats",
  551: "Colorful pastel",
  553: "REVOLUTION",
  554: "Right on time (Ryu * Remix)",
  557: "Nagisa no koakuma lovely\~radio",
  561: "Chikuwa parfait da yo CKP",
  562: "Rin to shite saku hana no gotoku \~ HinaBitter edition \~",
  566: "Turn! Setsugetsuka",
  568: "Mind game",
  572: "Koi hadou? Moro hadou OK houteishiki!!",
  573: "Yamato nadenade Kaguya-hime",
  574: "Hoshikuzu no kiroku",
  576: "Deadball de Homerun",
  578: "Yakyuu no asobikata soshite sono rekishi -ketteiban-",
  579: "Todoroke! Koi no beanball!!",
  587: "AETHER",
  590: "MITOrete! Ibarakisshu dar-ling",
  592: "Chewin Bunny",
  595: "Setsuna Trip",
  596: "Luckgakist",
  597: "Bamboo Sword Girl",
  598: "Gensoukei sekaishuufuku shoujo",
  600: "Dokidoki ryuusei trap girl!!",
  601: "Strobe Girl",
  607: "Osenju Meditation",
  610: "FUJIMORI FESTIVAL",
  614: "Nageki No Ki",
  615: "Burning Beach Side Bunny",
  616: "Awaodori yappari odori wa yamerarenai",
  626: "Endorphin",
  627: "Go\↓Go\↑Girls\&Boys!",
  629: "Crimson Gate",
  630: "Wadatsumi",
  639: "HAPPY LUCKY YEAPPY",
  642: "Otome ryouran mai sakihokore",
  643: "Metsubou tenshi nikokyuppin",
  644: "Mirai prism",
  648: "Over the \"Period\"",
  649: "Asairo no kamihikouki",
  651: "The disappearance of woman words",
  655: "Homeneko sensation",
  656: "Mysterious - Ayakashi Kakushi -",
  657: "Chocolate Smile",
  658: "BeBeatStream",
  659: "Totsugeki! Glass no kneeso hime!",
  660: "Bakunana testroyer",
  667: "Pa\→Pi\→Pu\→Yeah!",
  661: "Dopamine",
  665: "Tenkuu no Hana",
  668: "Summer Color DIARY -DDR mix-",
  671: "Gekiatsu majiyaba cheer girl",
  672: "Hanamaru pippi wa yoiko dake",
  673: "Special jet princess Sunday",
  674: "Region Creation \☆ Chikuwakutics",
  676: "Cirno\'s Perfect Math Class (EDM REMIX)",
  677: "Night of Knights",
  678: "Marisa stole the precious thing",
  683: "Kyun kyun bakkyun LOVE",
  678: "Marisa stole the precious thing",
  684: "Sayonara trip \~ Natsuhi EDM edition \~",
  685: "Sanctuary of the 12 constellations",
  691: "Oboro",
  692: "Under this blue sky",
  693: "Dadadadadadadadadada",
  694: "ALL MY HEART -kono koi ni, watashi no subete wo kakeru-",
  696: "Ha-lle-lu-jah",
  701: "Kurokami midareshi shura to narite - Rin edition -",
  702: "Iro wa nioedo chirinuru wo",
  703: "After School Stride",
  704: "Happy synthesizer",
  705: "One-way ticket to the universe (Sora)",
  718: "Kuranogawa ondo",
  720: "Happy koi lovely time!!",
  723: "Bassdrop Freaks",
  725: "Ama no jyaku",
  726: "Rokuchounen to ichiya monogatari",
  727: "Lost one no goukoku",
  747: "Love is the Space War!",
  748: "Renaikansoku",
  753: "Exciting!! Mo - cha - cha",
  754: "Ronron e rairairai!",
  759: "Nou shou sakuretsu girl",
  760: "Disappearance of Hatsune Miku",
  767: "Strawberry Chu Chu",
  773: "Shakariki relation",
  781: "Role-playing game",
  782: "Alien alien",
  783: "Koishigure",
  784: "Yi-er fanclub",
  785: "Roshin yuukai",
  786: "Shunpuu blowing wind",
  790: "Sennen no kotowari",
  791: "Plain Asia -PHQ remix-"
}