module.exports = {
  8: "KEEP ON MOVIN\'",
  9: "PARANOiA KCET \~ clean mix \~",
  19: "GRADIUSIC CYBER \~ AMD G5 MIX \~",
  20: "La Se\ñorita",
  21: "La Se\ñorita Virtual",
  22: "LOVE THIS FEELIN \'",
  26: "TRIP MACHINE \~luv mix\~",
  52: "CAN\'T STOP FALLIN IN LOVE(SPEED MIX)",
  60: "SANA MOLLETE NE ENTE",
  61: "CANDY *",
  63: "Healing Vision - Angelic Mix -",
  66: "Orion.78\~civilization mix\~",
  74: "CANDY \♡",
  83: "i feel...",
  96: "Kakumei",
  98: "LOVE LOVE SUGAR",
  106: "Colors \~ for EXTREME \~",
  111: "Frozen Ray \~for EXTREME \~",
  113: "GRADUATION \~each tomorrow\~",
  115: "Heaven is a \'57 metallic gray \~gimmix\~",
  117: "I\'m gonna get you!",
  123: "L\'amour et la liberte(DDR Ver.)",
  124: "LOVE SHINE",
  125: "Miracle Moon \~L.E.D.LIGHT STYLE MIX\~",
  142: "Mikeneko rock",
  143: "Blue Impugle \~for EXTREME \~",
  138: "V \~for EXTREME \~",
  141: "Sakura",
  144: "Daikenkai",
  149: "Ballad for you \~omoi no ame\~",
  153: "CAN\'T STOP FALLIN IN LOVE - super euro version -",
  159: "Fascination \~eternal love mix\~",
  168: "HAPPY ANGEL",
  174: "Jam \& Marmalade",
  175: "KEEP ON MOVIN\' \~DMX MIX\~",
  180: "MARIA(I believe...)",
  193: "PUT YOUR FAITH IN ME \~SATURDAY NIGHT MIX\~",
  205: "STARS \☆\☆\☆ (2nd NAOKI\'s style)",
  210: "TRUE LOVE",
  216: "Kagerou",
  217: "Konoko no nanatsu no oiwaini",
  218: "Chikara",
  219: "Himawari",
  220: "Hana Ranman -Flowers-",
  221: "Gekkou chou",
  222: "DAN-DAN-DO",
  223: "Tino\'s White Horse",
  224: "Nijiiro",
  225: "Mugen",
  227: "AM-3P (CHAOS Special)",
  229: "B4U (VOLTAGE Special)",
  232: "BRILLIANT 2U (STREAM Special)",
  233: "CaptivAte - Chikai",
  234: "D2R (FREEZE Special)",
  235: "DEAD END (GROOVE RADAR Special)",
  237: "DYNAMITE RAVE (AIR Special)",
  240: "Feelings Won\'t Fade(Extend Trance Mix)",
  242: "Flow (Jammin\' Ragga Mix)",
  245: "GiriGili monzen jakura",
  246: "L\'amour et la liberte(DDR Ver.)",
  255: "Raspberry Heart (English version)",
  261: "STARS \☆\☆\☆ (Re-turned by HAL) -DDR EDITION-",
  263: "SUNKISS DROP",
  273: "Votun stellarum -forest \# 25 DDR RMX-",
  280: "CANDY \☆ (X-Special)",
  303: "PARANOiA MAX \~ DIRTY MIX \~ (X-Special)",
  314: "SP-TRIP MACHINE \~ JUNGLE MIX \~ (X-Special)",
  329: "Ubertreffen",
  332: "Polyrhythm",
  333: "Kakumei (X-Special)",
  334: "Zero - ZERO -",
  335: "Rin to shite saku hana no gotoku",
  337: "shining",
  346: "Dazzlin\' Darlin -Akiba koubou mix-",
  359: "I\'m So Happy",
  361: "KIMONO PRINCESS",
  362: "KISS KISS KISS Akiba koubou MIX",
  390: "smooooch",
  391: "someday...",
  401: "ZETA \~sosuu no sekai to chouetsusha\~",
  402: "Delta MAX",
  403: "Fuchinkan CANDY",
  404: "Mei",
  405: "Beautiful Receipt",
  409: "Memeshikute",
  441: "I \/ O",
  427: "CRAZY LOVE",
  428: "Sumidagawa karenka",
  452: "Tenjoy no hoshi \~reimeiki\~",
  453: "Terrible Hit Chart",
  454: "Shizuku",
  455: "TWINKLE HEART",
  456: "Alstroemeria (walk with you remix)",
  458: "SILVER DREAM",
  459: "osaka EVOLVED - maido, ohkini! - (TYPE 1)",
  460: "osaka EVOLVED - maido, ohkini! - (TYPE 2)",
  461: "osaka EVOLVED - maido, ohkini! - (TYPE 3)",
  482: "KEEP ON MOVIN (Y Co. DJ BOSS remix)",
  483: "PUT YOUR FAITH IN ME (DA\'s Twinkly Disco Remix)",
  489: "Kouen",
  491: "Rensen ryouran",
  492: "Qipchaq",
  495: "Meumeupettantan",
  505: "Orenai heart",
  527: "Rakiraki",
  528: "Seiten Bon Voyage",
  530: "Nijiiro no hana",
  531: "Okome no oishii takikata, soshite okome wo taberu koto ni yoru sono kouka.",
  532: "Genesis Notes",
  541: "JoJo ~sono chi no sadame~",
  542: "Furisodation",
  549: "Kiken na kajitsu",
  550: "Who floats",
  551: "Colorful pastel",
  553: "REVOLUTION",
  554: "Right on time (Ryu * Remix)",
  557: "Nagisa no koakuma lovely\~radio",
  561: "Chikuwa parfait da yo CKP",
  562: "Rin to shite saku hana no gotoku \~ HinaBitter edition \~",
  566: "Turn! Setsugetsuka",
  568: "Mind game",
  572: "Koi hadou? Moro hadou OK houteishiki!!",
  573: "Yamato nadenade Kaguya-hime",
  574: "Hoshikuzu no kiroku",
  576: "Deadball de Homerun",
  578: "Yakyuu no asobikata soshite sono rekishi -ketteiban-",
  579: "Todoroke! Koi no beanball!!",
  587: "AETHER",
  590: "MITOrete! Ibarakisshu dar-ling",
  592: "Chewin Bunny",
  595: "Setsuna Trip",
  596: "Luckgakist",
  597: "Bamboo Sword Girl",
  598: "Gensoukei sekaishuufuku shoujo",
  600: "Dokidoki ryuusei trap girl!!",
  601: "Strobe Girl",
  607: "Osenju Meditation",
  610: "FUJIMORI FESTIVAL",
  614: "Nageki No Ki",
  615: "Burning Beach Side Bunny",
  616: "Awaodori yappari odori wa yamerarenai",
  626: "Endorphin",
  627: "Go\↓Go\↑Girls\&Boys!",
  629: "Crimson Gate",
  630: "Wadatsumi",
  639: "HAPPY LUCKY YEAPPY",
  642: "Otome ryouran mai sakihokore",
  643: "Metsubou tenshi nikokyuppin",
  644: "Mirai prism",
  648: "Over the \"Period\"",
  649: "Asairo no kamihikouki",
  651: "The disappearance of woman words",
  655: "Homeneko sensation",
  656: "Mysterious - Ayakashi Kakushi -",
  657: "Chocolate Smile",
  658: "BeBeatStream",
  659: "Totsugeki! Glass no kneeso hime!",
  660: "Bakunana testroyer",
  667: "Pa\→Pi\→Pu\→Yeah!",
  661: "Dopamine",
  665: "Tenkuu no Hana",
  668: "Summer Color DIARY -DDR mix-",
  671: "Gekiatsu majiyaba cheer girl",
  672: "Hanamaru pippi wa yoiko dake",
  673: "Special jet princess Sunday",
  674: "Region Creation \☆ Chikuwakutics",
  675: "EDM jumpers",
  676: "Cirno\'s Perfect Math Class (EDM REMIX)",
  677: "Night of Knights",
  678: "Marisa stole the precious thing",
  683: "Kyun kyun bakkyun LOVE",
  678: "Marisa stole the precious thing",
  684: "Sayonara trip \~ Natsuhi EDM edition \~",
  685: "Sanctuary of the 12 constellations",
  686: "Mahou no tamage \~Cocona ELECTRO POP edition\~",
  691: "Oboro",
  692: "Under this blue sky",
  693: "Dadadadadadadadadada",
  694: "ALL MY HEART -kono koi ni, watashi no subete wo kakeru-",
  696: "Ha-lle-lu-jah",
  701: "Kurokami midareshi shura to narite - Rin edition -",
  702: "Iro wa nioedo chirinuru wo",
  703: "After School Stride",
  704: "Happy synthesizer",
  705: "One-way ticket to the universe (Sora)",
  718: "Kuranogawa ondo",
  720: "Happy koi lovely time!!",
  723: "Bassdrop Freaks",
  725: "Ama no jyaku",
  726: "Rokuchounen to ichiya monogatari",
  727: "Lost one no goukoku",
  747: "Love is the Space War!",
  748: "Renaikansoku",
  753: "Exciting!! Mo - cha - cha",
  754: "Ronron e rairairai!",
  758: "Shiawase ni nareru kakushi command ga arurashii",
  759: "Nou shou sakuretsu girl",
  760: "Disappearance of Hatsune Miku",
  761: "Cirno\'s Perfect Math Class",
  762: "Himawari sunset",
  763: "Kunshi ayauku mo chikou yore",
  766: "Koi no puzzle magic",
  767: "Strawberry Chu\♡Chu\♡",
  768: "Youkoso Japari Park e",
  769: "Rinnetensei",
  772: "Luminous days",
  773: "Shakariki relation",
  774: "Tatakae! Dadandarn V",
  775: "Haru ichiban",
  781: "Role-playing game",
  782: "Alien alien",
  783: "Koishigure",
  784: "Yi-er fanclub",
  785: "Roshin yuukai",
  786: "Shunpuu blowing wind",
  790: "Sennen no kotowari",
  791: "Plain Asia -PHQ remix-",
  793: "Oboro (dj TAKA Remix)",
  795: "Onegai darling",
  796: "Buraikku jokorizer"
}